### PR TITLE
Unfiltered and Filtered Recipe Searches using API

### PR DESCRIPTION
**Pull request by rickychen175**
I have added methods for creating a request URL from a list of ingredients and getting the API response.
This API provider can be found here: [https://developer.edamam.com/edamam-docs-recipe-api]( https://developer.edamam.com/edamam-docs-recipe-api)

### CODE REVIEW

**Review by fishyvishy — APPROVED** [review]
The recipe options entity will need modification when the filtering system is implemented. Not fully sure whether utilities directory is necessary, but it does seem convenient. Looks good otherwise.

**Review by EricKarpovits — APPROVED** [review]
Looks great!

**Review by fonuxxine — APPROVED** [review]
The structure follows Clean Architecture principles. Looks good.

**Comment by fonuxxine** [comment]
The .idea/misc.xml is not supposed to be pushed onto the main branch.

**Pull request merged**
