### PR TITLE
Dependency errors fixed 

### PR DESCRIPTION
**Pull request by fishyvishy**
Login, Register, and Search formatter were accessing recipe entities directly. Code modified to ensure entity access occurs only in use cases. IntelliJ dependency viewer shows presenters now have no dependence on entities.

### CODE REVIEW

**Review by EricKarpovits — APPROVED** [review]
Amazing @fishyvishy

**Review by Shaffaan — APPROVED** [review]
Good work vishwanath

**Review by takeachangs — APPROVED** [review]
Way to go vish!

**Review by rickychen175 — APPROVED** [review]
Good Job

**Pull request merged**
