### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by EricKarpovits**
I updated the README for milestone 4. Adding specifications, about us, and how to run the program area.

Let me know if there is something I should change. 

Screen Shot 2022-11-21 at 5 17 12 PM

### CODE REVIEW

**Review by RedFoxity — APPROVED** [review]
Everything looks good!

**Comment by Zhuofan-Y** [comment]
Solid writing Eric!

**Review by Zhuofan-Y — APPROVED** [review]
Solid writing

**Review by Shaffaan — APPROVED** [review]
Great work eric, we need to defend our design choices and talk about that in detail. Will do that for milestone 5

**Pull request merged**
