### PR TITLE
Create Fridge class that can add and remove ingredients. Ingredients …

### PR DESCRIPTION
**Pull request by fonuxxine**
Create Fridge class that can add, remove, load ingredients. Create Ingredient class with its name.

### CODE REVIEW

**Review by Shaffaan — APPROVED** [review]
I have reviewed the changes, later when we start implementing further we will need to modify this class and add more methods.

**Review by EricKarpovits — CHANGES_REQUESTED** [review]
Please add docstring comments to each method.

**Review by EricKarpovits — APPROVED** [review]

**Comment by fishyvishy** [comment]
Looks good. Will likely need additional method to check if ingredient is unique.

**Review by fishyvishy — APPROVED** [review]
Looks good. Will likely need additional method to check if ingredients are unique.

**Review by RedFoxity — APPROVED** [review]
Everything looks good with the Fridge and Ingredient objects.

**Pull request merged**
